### ISSUE TITLE
The Docker build are failing

### ISSUE THREAD

**Issue by kazoompa** [nfdi4health/metadata-annotation-workbench#6]
Hi,

I have started looking into this repository and tried to build the dev and prod without success.

This  Dev step generated the following error:
```
[~/projects/mlstr/metadata-annotation-workbench] main
>docker compose --env-file dev.env up prediction
[+] Running 0/1
 ⠿ prediction Error                                                                                                                                                                                           1.4s
Error response from daemon: Get "https://gitlab.zbmed.de:5050/v2/": dial tcp 134.95.56.228:5050: connect: connection refused
```

And when I tried the Prod steps to build and load the containers had this error:
```
[~/projects/mlstr/metadata-annotation-workbench] main
>docker compose --env-file dev.env build
[+] Building 1.1s (15/20)                                                                                                                                                                                          
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/backend:dev internal] load build definition from Dockerfile                                                                                     0.1s
 => => transferring dockerfile: 347B                                                                                                                                                                          0.0s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev internal] load build definition from Dockerfile                                                                                    0.1s
 => => transferring dockerfile: 374B                                                                                                                                                                          0.0s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev internal] load metadata for docker.io/library/nginx:alpine                                                                         0.5s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/backend:dev internal] load metadata for docker.io/library/python:3.8                                                                            0.5s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev internal] load .dockerignore                                                                                                       0.1s
 => => transferring context: 3.88kB                                                                                                                                                                           0.0s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/backend:dev internal] load .dockerignore                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev internal] load build context                                                                                                       0.1s
 => => transferring context: 2.39kB                                                                                                                                                                           0.0s
 => CANCELED [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 1/6] FROM docker.io/library/nginx:alpine@sha256:a5127daff3d6f4606be3100a252419bfa84fd6ee5cd74d0feaca1a5068f97dcf          0.2s
 => => resolve docker.io/library/nginx:alpine@sha256:a5127daff3d6f4606be3100a252419bfa84fd6ee5cd74d0feaca1a5068f97dcf                                                                                         0.1s
 => => sha256:a5127daff3d6f4606be3100a252419bfa84fd6ee5cd74d0feaca1a5068f97dcf 9.07kB / 9.07kB                                                                                                                0.0s
 => => sha256:074604130336e3c431b7c6b5b551b5a6ae5b67db13b3d223c6db638f85c7ff56 2.50kB / 2.50kB                                                                                                                0.0s
 => => sha256:c7b4f26a7d93f4f1f276c51adb03ef0df54a82de89f254a9aec5c18bf0e45ee9 11.21kB / 11.21kB                                                                                                              0.0s
 => CANCELED [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/backend:dev 1/6] FROM docker.io/library/python:3.8@sha256:ecd06b59ae52c021ae58b8fea0957bf5b0f4568783cb0240b56e06ed1720cc19             0.4s
 => => resolve docker.io/library/python:3.8@sha256:ecd06b59ae52c021ae58b8fea0957bf5b0f4568783cb0240b56e06ed1720cc19                                                                                           0.2s
 => => sha256:ad4a9aed1d241d025af20a3abb37c4adc6084a13ea1c33391ab55a737b578faa 2.52kB / 2.52kB                                                                                                                0.0s
 => => sha256:f5c5013453fab04241dca0dc61a4629a2cfe731e7411e6b5f81af77d70798c3d 7.32kB / 7.32kB                                                                                                                0.0s
 => => sha256:ecd06b59ae52c021ae58b8fea0957bf5b0f4568783cb0240b56e06ed1720cc19 10.35kB / 10.35kB                                                                                                              0.0s
 => => sha256:8cd46d290033f265db57fd808ac81c444ec5a5b3f189c3d6d85043b647336913 0B / 49.56MB                                                                                                                   0.1s
 => [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/backend:dev internal] load build context                                                                                                        0.1s
 => => transferring context: 481.25kB                                                                                                                                                                         0.0s
 => CACHED [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 2/6] COPY nginx.conf /etc/nginx/templates/default.conf.template                                                             0.0s
 => CACHED [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 3/6] COPY nginx-server.conf /etc/nginx/nginx.conf                                                                           0.0s
 => CACHED [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 4/6] COPY setVariables.sh /docker-entrypoint.d/50-insert-runtime-variables.sh                                               0.0s
 => CACHED [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 5/6] RUN chmod +x /docker-entrypoint.d/50-insert-runtime-variables.sh                                                       0.0s
 => ERROR [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 6/6] COPY build /usr/share/nginx/html                                                                                        0.0s
------
 > [gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:dev 6/6] COPY build /usr/share/nginx/html:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref LRU2:AC73:O6ET:327Y:2BOT:WPUG:WB6N:2IN3:IKBI:JXD6:XMHE:WGG3::qvacx99mpnh2j2xdvg00i5hvv: "/build": not found
[~/projects/mlstr/metadata-annotation-workbench] main
```

Here are more info:
- Python 3.9.2
- Docker version 27.2.1, build 9e34c9b
- NPM: v18.17.1 (lts/hydrogen)

Thanks for the great effort building this, I would love to learn more about and try it locally.

Any help is greatly appreciated.

**Comment by jusa3** [comment]
Thanks for reporting. The projects moved and I updated the image paths accordingly. This should fix the issue with the dev setup.

Before doing the Docker build, a local build step is needed. I updated the README. This should fix the production setup.

**Comment by kazoompa** [comment]
Hi, 

I still have access issue for creating the container:

```
>docker compose --env-file dev.env up prediction
[+] Running 0/1
 ⠿ prediction Error                                                                                                                               0.5s
Error response from daemon: Head "https://ghcr.io/v2/nfdi4health/workbench-ai-
model/backend/manifests/e57e38ff84b682be298d936ab7338f0fb9502825": denied: denied
```

Are there also any tutrial or documentation on how to use the tool to get the a beginner start?

Best,

**Comment by jusa3** [comment]
You can find a tutorial/documentation at https://mda.nfdi4health.de/tutorial. It's not quite up to date, but it's a good place to start.
